name: E2E Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create workspace
        id: workspace
        uses:  TakeScoop/terraform-cloud-workspace-action@v2
        with:
          terraform_organization: takescoop-oss
          terraform_token: ${{ secrets.TF_TOKEN_OSS }}
          name: remote-state-action-e2e-test
          apply: true
          working_directory: test-e2e/
          vcs_type: github

      - name: Run action
        id: action
        uses: ./
        with:
          workspace: remote-state-action-e2e-test
          organization: takescoop-oss
          token: ${{ secrets.TF_TOKEN_OSS }}
      
      - run: test "${{ steps.action.outputs.foo }}" == "bar"
      - run: echo "${{ steps.action.outputs.foo }}"
      - run: test "${{ fromJson(steps.action.outputs.json).foo }}" == "bar"
      - run: test "${{ steps.action.outputs.sensitive }}" == "secret"
      - run: |
          stars=$(echo "${{ steps.action.outputs.sensitive }}")
          echo $stars
          test "$stars" == "***"
